name: shopesapp
description: A new Flutter project.

publish_to: "none"


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter_markdown_latex: ^0.3.2
  animations: ^2.0.7
  awesome_dialog: ^3.1.0
  bot_toast: ^4.0.4
  cached_network_image: ^3.2.3
  connectivity_plus: ^4.0.2
  cupertino_icons: ^1.0.5
  device_preview: ^1.1.0
  easy_localization: ^3.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_launcher_icons: ^0.13.1
  flutter_settings_screens: ^0.3.3-null-safety+2
  flutter_speed_dial: ^7.0.0
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.5
  font_awesome_flutter: null
  geocoding: ^2.1.0
  google_fonts: ^4.0.4
  google_maps_flutter: ^2.3.0
  grouped_list: ^5.1.2
  http: ^0.13.6
  hydrated_bloc: ^9.1.2
  image_picker: ^1.0.2
  location: ^5.0.2+1
  mime: ^1.0.4
  path_provider: ^2.0.15
  pin_code_fields: ^8.0.1
  rating_dialog: ^2.0.4
  shared_preferences: ^2.2.0
  sizer: ^2.0.15
  url_launcher: ^6.1.11

dev_dependencies:

  flutter_lints: ^2.0.2
  flutter_native_splash: ^2.2.19
  flutter_test:
    sdk: flutter
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/storopedia_logo.jpg"
  adaptive_icon_foreground: "assets/storeopedia_foreground.png"
  adaptive_icon_background: "#ffffff"

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/translations/

